[package]
name = "rlp"
version = "0.1.0"
authors = ["edwardtanshuo <tanshuo198956@gmail.com>"]

[dependencies]
bytebuffer = "0.2.1"
lazy_static = "1.0.0"
serde = "1.0.33"
serde_json = "1.0.13"

gen_utils = { version = "0.1.0", path = "../util" }